### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#13]
**Team**
- [x] README quality, release day policies, Scrum Board to week after break
- [ ] Deployed Web Site (recieved extension)

**Individual**
- [x] [Mahima](https://github.com/yolandayangg/n224p4-beans/projects/1#card-73172087)
- [x] [Nayana](https://github.com/yolandayangg/n224p4-beans/projects/1#card-73172049)
- [x] [Natalie](https://github.com/yolandayangg/n224p4-beans/projects/1#card-73172097)
- [x] [Shruti](https://github.com/yolandayangg/n224p4-beans/projects/1#card-73172086)
- [x] [Yolanda](https://github.com/yolandayangg/n224p4-beans/projects/1#card-73172083)

**TPT**
- [x] Create Task plan
- [x] CB 2.3 and 2.4 quizzes

**Comment by shrutiapcsp** [comment]
Team
README quality, release day policies, Scrum Board to week after break

- [ ]  1.0
- [ ] .75
- [ ] .5
- [ ] 0
Justification:
Deployed Web Site

- [ ]  1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification:
Individual
About Page must Extend from Layout and have special customization (color pallet, background, etc)

 1.0
 .75
 .5
 0
Justification:
Picture with Mask that toggles to Picture of Choice (ie pic without mask)

 1.0
 .75
 .5
 0
Justification:
Pull or show data (Web API) with information of interest

 1.0
 .75
 .5
 0
Justification:
Establish link(s) to journal and other key indicators of your work and progress (remember pop quiz). TPT Link to Create Task planning

 1.0
 .75
 .5
 0
Justification:
Create Task plan

 1.0
 .75
 .5
 0
Justification:
2.3 Extracting Information from Data, 2.4 Using Programs with Data

 1.0
 .75
 .5
 0
Justification:

**Comment by suneelanaidu** [comment]
Your APIs: All of you hard coded some data into the HTML/JS function. Technically that's not an API. Data from backend(py) must be fed to frontend(HTML). See Jokes/Covid examples on csp.nighthawkcodingsociety.com.
