### ISSUE TITLE
Week 3 Live Review

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#14]
**Design Manager**
- [x] Bootstrap layouts
- [x]  [at least 3 frontend screens screens with functionality toward Project Theme](https://github.com/yolandayangg/n224p4-beans/commit/2be8a29561957f0968b62b0e50da7ff77372b179)
- [x] [Source link](https://github.com/yolandayangg/n224p4-beans/blob/main/templates/layouts/base.html)

**Scrum Master**
- [x]  overview of progress using GitHub README, Tickets (Completed and Backlog), and Wiki
- [x] Show expected backlog when returning from Winter Break.

**Technical officer** 
- [x] Asynchronous access(es) to a Database (Search and/or a CRUD operations).
- [x] [Runtime link to CRUD page](http://127.0.0.1:8000/crud/)
- [x] [View](https://github.com/nighthawkcoders/nighthawk_csp/blob/master/crud/templates/crud/search.html)
- [x] [Model](https://github.com/nighthawkcoders/nighthawk_csp/blob/master/crud/model.py)

**Deployment manager** 
- [x] Web Site running from URL (https)
- [x] demonstrating the process to perform an update.

**GitHub admin**
- [x]  highlighting commits and pull requests completed by each individual.
- [Mahima](https://github.com/yolandayangg/n224p4-beans/commits?author=mahimak19)
- [Natalie](https://github.com/yolandayangg/n224p4-beans/commits?author=nataliecohen)
- [Nayana](https://github.com/yolandayangg/n224p4-beans/commits?author=Nayanav)
- [Shruti](https://github.com/yolandayangg/n224p4-beans/commits?author=shrutiapcsp)
- [Yolanda](https://github.com/yolandayangg/n224p4-beans/commits?author=yolandayangg)
- [Pull request instructions](https://github.com/yolandayangg/n224p4-beans/wiki/Github-Admins-policy-document:)
- [Branching procedures](https://github.com/yolandayangg/n224p4-beans/wiki/Deployment-Guide)

**Technical Officer and Scrum Master**
- [x] 1 minute video on Asynchronous Data Access, PBL, plans post Winter Break

**Comment by shrutiapcsp** [comment]
**Team Section.**
Scrum Master and Technical Officer
PBL Highlights.  <readme time box link>
[Video](https://drive.google.com/file/d/16tztvsZ2qZfGM1ziiCqOaCXgUZBQ1a8o/view?usp=sharing)

Design Manager tangibles
Layout. <source link>
Front End Feature Screen <[source link](https://github.com/yolandayangg/n224p4-beans/commit/2be8a29561957f0968b62b0e50da7ff77372b179)> <runtime link>
Front End Screen 2: <runtime link>
Front End Screen 3: <runtime link>

Scrum Master tangibles
GitHub Scrum Board <tickets in review link> <[in progress link](url)>
Scrum Board <post winter break backlog link>

Technical officer tangibles
Database with CRUD:
Runtim <link to CRUD page runtime>
View <link to code supporting crud routes and logic>
Model <link to class and crud>

Deployment manager tangibles
Update procedure: <link to deployment guid that contains procedure for someone to make an update to deployment>
Nginx config: <link to deployment guide containing paste of configuration file>
Service config: <link to deployment guide containing paste of service file>

GitHub admin tangibles
Commit, pull request procedure <link to deployment guide that shows process>
Branching procedure <l[ink to deployment guide that show process to create and merge a branch](https://github.com/yolandayangg/n224p4-beans/wiki/Deployment-Guide)>

**Individual Section.**
AP MCQ Test and Corrections <link to results>

**Comment by shrutiapcsp** [comment]
Self Grade

Group grade: 5.75/6- some missing of Deployment
Individual
Mahima: 2/2
Natalie: 2/2
Nayana: 2/2
Shruti: 2/2
Yolanda: 2/2

Grade for each person 7.75/8

**Comment by suneelanaidu** [comment]
Overall nice job and good team work. Try to stick to time given for videos.
This site can’t be reached. Do you have a Domain name yet?
