### ISSUE TITLE
Yolanda Week 4 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#32]
1. Attendance, tutorial makeup if missing time, activity, individual questions, work habits, tutorial if behind.
2. Individual Runtime review on About Page progress/quality.
3. Individual Analytics (Issues with Tangibles, Commits)
4. CB progress, focus is on CB-exam MCQ test and improvement plan
5. Expertise in one or more of the following...  Procedures, Blueprint, Jekyll, Deployment Certbot, Databases, Wikie Policies, Branching strategies,	SCSS, Async with Fetch

**Comment by yolandayangg** [comment]
Score: 3.5/5

Focus for next week:
- understanding of material: jekyll, CRUD, databases, etc
- more involvement in the classroom: tutorial, asking other teams for help.
