### ISSUE TITLE
Week 5 and 7 PBL Showing

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#42]
- [ ] PBL key features: [personality quiz](https://github.com/yolandayangg/n224p4-beans/commit/2fede5e0204501218f2a54a79cd079cd1c8bafb3), fun facts about personality types, slideshow of images
- [ ] Github Pages, Jekyll, WIKI - [quality of Vocabulary from Week 6](https://github.com/yolandayangg/n224p4-beans/wiki/Week-6-Competency-Terms) 
- [ ] Sassy / Bootstrap - CSS usage and Bootstrap features, runtime quality
- [ ] Async Operation - runtime and usage of JavaScript and Fetch
- [ ] CRUD in Database - runtime and behind the scenes using CRUD operations, database personalization
- [ ] [Blueprint Demonstration](https://github.com/yolandayangg/n224p4-beans/commit/dcad5d417fd4afcd65caa6b2915167090042f898)

**Comment by ProRichyMan** [comment]
Grade for Review ticket:
-0.75 for runtime of CRUD operations (+0.75 replaced with Blueprint illustration)
-0.25 for Sassy 

Final grade: 5.75/6

https://www.veed.io/view/290582cb-6da7-464a-8830-cc947e92617e
