### ISSUE TITLE
Week 1 Review Ticket

### ISSUE THREAD

**Issue by shrutiapcsp** [yolandayangg/n224p4-beans#9]
**Scrum Team Project Review**

- [x] Design - Wiki Theme, Brain Write & Wire Frame
- [x] Technicals - 10 to 12 key ideas
- [x] Github - On Wiki containing Management Plan
- [x] Discussion of policies on other page in wiki
- [x] Deployment - Wiki Plan, Hardware and Frequency
- [x] Scrum Board - Assignments and Backlog
Individual TPT Issue

Individual Create Task Understanding and Score, Notes, on TPT

- [x] TPT 0.0, Create Task ideas, notes, and research
- [x] 1.3 Program Design and Development
- [x] 1.4 Identifying and Correcting Errors

**Comment by ProRichyMan** [comment]
- [ ] Design - Wiki Theme, Brain Write & Wire Frame
Tangible: [Link](https://github.com/yolandayangg/n224p4-beans#ideation) [Link](https://github.com/yolandayangg/n224p4-beans/wiki/Wireframe)
- [ ] Technicals - 10  to 12 key ideas 
Tangible: [Link](https://github.com/yolandayangg/n224p4-beans/wiki/Technicals)
- [ ] Github - On Wiki containing Management Plan
Tangible: [Link](https://github.com/yolandayangg/n224p4-beans/wiki/BOF-Github-Admins-policy-document:)
- [ ] Deployment - Wiki Plan, Hardware and Frequency
Tangible: [Link](https://github.com/yolandayangg/n224p4-beans/wiki/Deployment-Guide)
- [ ] Scrum Board - Assignments and Backlog
Tangible: [Link](https://github.com/yolandayangg/n224p4-beans/projects/1)
- [ ] TPT 0.0, Create Task ideas, notes, and research
Tangible: [Link](https://docs.google.com/document/d/1u8SX84sg8QsT7gzVuCX_T-uksLZDLLriqrIEiLrn0aw/edit)
- [ ] 1.3 Program Design and Development
Tangible: [Link](https://docs.google.com/document/d/1u8SX84sg8QsT7gzVuCX_T-uksLZDLLriqrIEiLrn0aw/edit)
- [ ] 1.4 Identifying and Correcting Errors
Tangible: [Link](https://docs.google.com/document/d/1u8SX84sg8QsT7gzVuCX_T-uksLZDLLriqrIEiLrn0aw/edit)

Score: 7.5/8
All items are pretty detailed and organized really well. The README is easy to navigate and the wiki contains all the necessary info needed. However, there was not evidence of Create Task ideas/notes for anybody other than Mahima, so I took away half a point.
